name: Colored Gifts
favicon: null
layout_spectrum: 0.13340681954286993
typography_spectrum: 0.5284902630373836
title: Culoare si emotie in fiecare cadou
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10132999811321497
  lightness: 0.5377413511741906
  saturation: 0.05963970604352653
  rhythmicContrast: 0.7935629156418145
purpose: []
